---
title: "Dynamic Linear Models"
subtitle: "FISH 507 – Applied Time Series Analysis"
author: "Mark Scheuerell"
date: "5 Feb 2019"
output:
  ioslides_presentation:
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
set.seed(123)
```

## Topics for today




## Simple linear regression

Let's begin with a linear regression model

$$
y_i = \alpha + \beta x_i + e_i ~ \text{with} ~ e_i \sim \text{N}(0,\sigma^2)
$$

The index $i$ has no explicit meaning--shuffling ($y_i,x_i$) pairs has no effect on parameter estimation


## Simple linear regression

We can write the model in matrix form

$$
y_i = \alpha + \beta x_i + e_i \\
\Downarrow \\
y_i = 
\begin{bmatrix}
  1 & x_i
\end{bmatrix}
\begin{bmatrix}
  \alpha \\
  \beta
\end{bmatrix} +
e_i
$$


## Simple linear regression

We can write the model in matrix form

$$
y_i = \alpha + \beta x_i + e_i \\
\Downarrow \\
y_i = 
\begin{bmatrix}
  1 & x_i
\end{bmatrix}
\begin{bmatrix}
  \alpha \\
  \beta
\end{bmatrix} +
e_i \\
\Downarrow \\
y_i = \mathbf{X}^{\top}_i \mathbf{\Theta} + e_i
$$

with $\mathbf{X}^{\top}_i = \begin{bmatrix} 1 & x_i \end{bmatrix}$ and $\mathbf{\Theta} = \begin{bmatrix} \alpha & \beta \end{bmatrix}^{\top}$ 


## Dynamic linear model (DLM)

In a _dynamic_ linear model, the regression parameters change over time, so we write

$$
y_i = \mathbf{X}^{\top}_i \mathbf{\Theta} + e_i ~~~~~~~ \text{(static)}
$$

as

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t ~~~~~~~ \text{(dynamic)}
$$


## Dynamic linear model (DLM)

There are 2 important points here:

$$
y_\boxed{t} = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t
$$

1. Subscript $t$ explicitly acknowledges implicit info in the time ordering of the data in $\mathbf{y}$  


## Dynamic linear model (DLM)

There are 2 important points here:

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_\boxed{t} + e_t
$$

1. Subscript $t$ explicitly acknowledges implicit info in the time ordering of the data in $\mathbf{y}$  

2. The relationship between $\mathbf{y}$ and $\mathbf{X}$ is unique for every $t$


## Constraining a DLM

Close examination of the DLM reveals an apparent problem for parameter estimation

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t
$$


## Constraining a DLM

Close examination of the DLM reveals an apparent problem for parameter estimation

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t
$$

We only have 1 data point per time step (ie, $y_t$ is a scalar)

__Thus, we can only estimate 1 parameter (with no uncertainty)!__


## Constraining a DLM

To address this issue, we'll constrain the regression parameters to be dependent from $t$ to $t+1$

$$
\mathbf{\Theta}_t = \mathbf{G}_t \mathbf{\Theta}_{t-1} + \mathbf{w}_t ~ \text{with} ~ \mathbf{w}_t \sim \text{MVN}(\mathbf{0}, \mathbf{Q})
$$


## Constraining a DLM

In practice, we often make $\mathbf{G}_t$ time invariant 

$$
\mathbf{\Theta}_t = \mathbf{G} \mathbf{\Theta}_{t-1} + \mathbf{w}_t
$$

or assume $\mathbf{G}_t$ is the identity matrix $\mathbf{I}$

$$
\begin{align}
  \mathbf{\Theta}_t &= \mathbf{I} \mathbf{\Theta}_{t-1} + \mathbf{w}_t \\
                    &= \mathbf{\Theta}_{t-1} + \mathbf{w}_t
\end{align}
$$

In the latter case, the parameters follow a random walk over time


## DLM in state-space form

Observation model relates covariates to data

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t
$$

State model determines how the parameters "evolve" over time

$$
\mathbf{\Theta}_t = \mathbf{G} \mathbf{\Theta}_{t-1} + \mathbf{w}_t
$$


## Example of a seasonal DLM

$$
y_t = \alpha_t + \beta_t x_t + \gamma_{qtr,t} + e_t \\
\gamma_t^{qtr} = 
\begin{cases}
  \gamma_{1,t} & \text{if } qtr = 1 \\
  \gamma_{2,t} & \text{if } qtr = 2 \\
  \gamma_{3,t} & \text{if } qtr = 3 \\
  \gamma_{4,t} & \text{if } qtr = 4
\end{cases}
$$

If we had quarterly data & wanted only the effects of

1. an intercept (level);  

2. one covariate; and  

3. the current quarter


## Example of a seasonal DLM

Full matrix form

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t \\
\mathbf{\Theta}_t = \mathbf{G} \mathbf{\Theta}_{t-1} + \mathbf{w}_t
$$

with

$$
\mathbf{X}^{\top}_t =
\begin{bmatrix}
  1 & x_t & 1 & 0 & 0 & 0
\end{bmatrix}
$$

and

$$
\mathbf{\Theta}_t^{\top} = 
\begin{bmatrix}
  \alpha_t & \beta_t & \gamma_{1,t} & \gamma_{2,t} & \gamma_{3,t} & \gamma_{4,t}
\end{bmatrix}
$$


## Example of non-diagonal $\mathbf{G}$

We can use a non-diagonal $\mathbf{G}$ to get the correct quarter effect

$$
\mathbf{G} = 
\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 0 & 0 & 1 \\
  0 & 0 & 1 & 0 & 0 & 0
\end{bmatrix}
~ \text{and} ~~
\mathbf{\Theta}_t = 
\begin{bmatrix}
  \alpha_t \\ \beta_t \\ \gamma_{i,t} \\ \gamma_{j,t} \\ \gamma_{k,t} \\ \gamma_{l,t}
\end{bmatrix}
$$


## Evolving parameters

$$
\underbrace{\begin{bmatrix}
  \alpha_1 \\ \beta_1 \\ \gamma_{1,1} \\ \gamma_{2,1} \\ \gamma_{3,1} \\ \gamma_{4,1}
\end{bmatrix}}_{\mathbf{\Theta}_1} =
\underbrace{\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 0 & 0 & 1 \\
  0 & 0 & 1 & 0 & 0 & 0
\end{bmatrix}}_{\mathbf{G}}
\underbrace{\begin{bmatrix}
  \alpha_0 \\ \beta_0 \\ \gamma_{4,0} \\ \gamma_{1,0} \\ \gamma_{2,0} \\ \gamma_{3,0}
\end{bmatrix}}_{\mathbf{\Theta}_0} + 
\underbrace{\begin{bmatrix}
  w_{\alpha,1} \\ w_{\beta,1}  \\ w_{\gamma_1,1}  \\ w_{\gamma_2,1} \\ w_{\gamma_3,1} \\ w_{\gamma_4,1}
\end{bmatrix}}_{\mathbf{w}_1}
$$


## Obtaining seasonal effect

$$
y_1 = 
\begin{bmatrix}
  1 & x_1 & 1 & 0 & 0 & 0
\end{bmatrix} 
\begin{bmatrix}
  \alpha_1 \\ \beta_1 \\ \gamma_{1,1} \\ \gamma_{2,1} \\ \gamma_{3,1} \\ \gamma_{4,1}
\end{bmatrix}
+ e_1
$$

$$
y_1 = \alpha_1 + \beta_1 x_1 + \gamma_{1,1} + e_1
$$


## Evolving parameters

$$
\underbrace{\begin{bmatrix}
  \alpha_2 \\ \beta_2 \\ \gamma_{2,2} \\ \gamma_{3,2} \\ \gamma_{4,2} \\ \gamma_{1,2}
\end{bmatrix}}_{\mathbf{\Theta}_2} =
\underbrace{\begin{bmatrix}
  1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 0 & 0 & 1 \\
  0 & 0 & 1 & 0 & 0 & 0
\end{bmatrix}}_{\mathbf{G}}
\underbrace{\begin{bmatrix}
  \alpha_1 \\ \beta_1 \\ \gamma_{1,1} \\ \gamma_{2,1} \\ \gamma_{3,1} \\ \gamma_{4,1}
\end{bmatrix}}_{\mathbf{\Theta}_1} + 
\underbrace{\begin{bmatrix}
  w_{\alpha,2} \\ w_{\beta,2}  \\ w_{\gamma_1,2}  \\ w_{\gamma_2,2} \\ w_{\gamma_3,2} \\ w_{\gamma_4,2}
\end{bmatrix}}_{\mathbf{w}_2}
$$


## Obtaining seasonal effect

$$
y_2 = 
\begin{bmatrix}
  1 & x_2 & 1 & 0 & 0 & 0
\end{bmatrix} 
\begin{bmatrix}
  \alpha_2 \\ \beta_2 \\ \gamma_{2,2} \\ \gamma_{3,2} \\ \gamma_{4,2} \\ \gamma_{1,2}
\end{bmatrix}
+ e_1
$$

$$
y_2 = \alpha_2 + \beta_2 x_2 + \gamma_{2,2} + e_2
$$


## DLM in MARSS notation

$$
y_t = \mathbf{X}^{\top}_t \mathbf{\Theta}_t + e_t \\
\mathbf{\Theta}_t = \mathbf{G} \mathbf{\Theta}_{t-1} + \mathbf{w}_t \\
\Downarrow \\
y_t = \mathbf{Z}_t \mathbf{x}_t + v_t \\
\mathbf{x}_t = \mathbf{B} \mathbf{x}_{t-1} + \mathbf{w}_t
$$


