---
title: "List of Labs"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# you can vector c() of things; pdf, rmd, video, data, key should be links
```

```{r}
emptylist <- list(
  title = "", topics ="", pdf = "", rmd = "",
  html = "", video = "", youtube = "",
  data = "", repo = "", 
  homework = "", key = "",
  instructor = "", hw_topics = "",
  hw_duedate = "")
fill.list <- function(...){
  inputlist <- list(...)
  x <- emptylist
  for(i in names(inputlist)){x[[i]] <- inputlist[[i]]}
  return(x)
}
```

```{r}
matrixlab <- fill.list(
 title = "Matrix math in R",
 topics = c("Matrices & matrix algebra","(review on your own)"),
 pdf = "",
 html = "https://atsa-es.github.io/atsa-labs/chap-basicmat.html",
 homework = "Optional: online tutorial <a href='https://atsa.shinyapps.io/matrix/'>Matrix tutorial</a>",
 key = "",
 hw_topics = "matrix math",
 hw_duedate = "Optional")
```

```{r}
lmlab <- fill.list(
  title = "Writing models in matrix form",
  topics = c("Writing models in matrix form (through section 2.5)"),
  html = c("https://atsa-es.github.io/atsa-labs/chap-mlr.html"),
  homework = "Optional (important to understand course material): Questions at end of <a href='https://atsa-es.github.io/atsa-labs/chap-mlr.html'>Chapter 2</a>. <a href='Labs/Week 1/HW_1_Key.html'>Key</a>",
  key = "Labs/Week 1/HW_1_Key.html",
  hw_topics = c("matrix models"),
  hw_duedate = "Optional"
)
```

```{r}
arimalab <- fill.list(
  title = "Box-Jenkins Methods",
  topics = c("Fitting ARIMA models", "Forecasting with ARIMA models"),
  html = c("Labs/Week 2/Lab1-ARIMA-2023.html"),
  data = "See repo",
  repo = "https://github.com/atsa-es/fish550-2023/tree/main/Lab-1",
  homework = "Lab write-up #1",
  key = "",
  instructor = "Eli",
  hw_topics = c("ARIMA models"),
  hw_duedate = "Due Tues Apr 18 11:59 PM PDT; Post to GitHub."
)
```

```{r}
sslab2 <- fill.list(
  title = "Multivariate State-space models",
  topics = c("Fitting mulitvariate state-space models"),
  pdf = "",
  rmd = "",
  html = c("https://atsa-es.github.io/atsa/Labs/Week%203/CR lab/Lab2-MARSS.html"),
  video = "",
  youtube = "",
  data = "See repo",
  repo = "https://github.com/atsa-es/fish550-2023/tree/main/Lab-1",
  homework = "Lab write-up #2",
  #homework = "HW #2 questions and data: [Rmd](https://atsa-es.github.io/atsa/Labs/Week 3/NO2Lab/HW2-NO2.Rmd), [html](https://atsa-es.github.io/atsa/Labs/Week 3/NO2Lab/HW2-NO2.html), [data](https://atsa-es.github.io/atsa/Labs/Week 3/NO2Lab/ECNNO2.RData), [Tips](https://atsa-es.github.io/atsa/Labs/Week 3/NO2Lab/HW2-Tips.html)",
  key = "",
  instructor = "Eli",
  hw_topics = c("State-space models"),
  hw_duedate = "Due Tues April 25 11:59 PM PDT; Post to GitHub"
)
```

```{r}
dfalab <- fill.list(
  title = "DFA models",
  topics = c("Fitting DFA models"),
  pdf = "",
  rmd = "",
  html = "Labs/Week 4/intro-to-dfa.html",
  video = "",
  youtube = "",
  data = "",
  homework = "Lab write-up #3",
  key = "",
  instructor = "Mark",
  hw_topics = c("Dynamic Factor Analysis"),
  hw_duedate = "Due Tues May 2 11:59 PM PDT; Post to GitHub"
)
```

```{r hmmlab}
hmmlab <- fill.list(
  title = "Hidden Markov Models",
  topics = c("HMMs"),
  pdf = "",
  rmd = "",
  html = "https://atsa-es.github.io/atsa/Labs/Week%205/Lab4_hmm.html",
  video = "",
  youtube = "",
  data = "[stoplight](https://atsa-es.github.io/atsa/Labs/Week%205/stoplight.csv)",
  homework = "Lab write-up #4: Hidden Markov Models. [Rmd](https://atsa-es.github.io/atsa/Labs/Week%205/Lab4_hmm.Rmd), [html](https://atsa-es.github.io/atsa/Labs/Week%205/Lab4_hmm.html)",
  key = "",
  instructor = "Eric",
  hw_topics = c(""),
  hw_duedate = "Due Tues May 9 11:59 PM PDT; Post to GitHub"
)
```

```{r}
dlmlab <- fill.list(
  title = "Dynamic Linear Models",
  topics = c("Fitting DLMs"),
  pdf = "",
  rmd = "Labs/Week 5/intro-to-dlms.Rmd",
  html = "Labs/Week 5/intro-to-dlms.html",
  video = "https://youtu.be/KpBgTqcsqNg",
  youtube = "",
  data = "",
  homework = "",
  key = "",
  instructor = "Mark",
  hw_topics = c("Dynamic Linear Models"),
  hw_duedate = "Due May 23 Tues 11:59 PM PDT; Post to GitHub"
)
```



```{r bayeslab}
bayeslab <- fill.list(
  title = "Fitting models non-Gaussian errors",
  topics = c("Fitting Bayesian state-space models",
              "Fitting zero-inflated models"),
  pdf = "",
  rmd = "https://atsa-es.github.io/atsa-labs/Rmds/fitting-models-with-stan.Rmd",
  html = "https://atsa-es.github.io/atsa-labs/chap-stan.html",
  video = "",
  youtube = "",
  data = "",
  homework = "Lab write-up # 5. Project Methods",
  key = "",
  instructor = "Eric",
  hw_topics = c(""),
  hw_duedate = "Due Fri May 12 11:59pm PDT; Post to GitHub"
)
```


```{r}
freqdomainlab <- fill.list(
  title = "Frequency Domain",
  topics = c("Frequency domain methods", "wavelet analysis", "Stochastic volatility"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "Lab write-up #6",
  key = "",
  instructor = "Mark",
  hw_topics = c(""),
  hw_duedate = "Due Tues May 23 11:59pm PDT; Post to GitHub"
)
```

```{r}
spatiallab <- fill.list(
  title = "Spatio-temporal models",
  topics = c("Spatio-temporal models"),
  pdf = "",
  rmd = "Labs/Week 9/lab.Rmd",
  html = "",
  video = "",
  youtube = "",
  data = c("[Data1](Labs/Week 9/SNOTEL_metadata.csv)", "[Data2](Labs/Week 9/SNOTEL_Washington_1981_2013.csv)", "[Data3](Labs/Week 9/tck_longform.Rdata)"),
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c(""),
  hw_duedate = "work on projects"
)
```

```{r help}
helplab <- fill.list(
  title = "TMB/C++ in R",
  topics = c("TMB", "C++"),
  pdf = "",
  rmd = "https://github.com/atsa-es/fish550-2023/tree/main/Lab-6",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eli",
  hw_topics = c("No homework"),
  hw_duedate = ""
)
```

```{r studentpresentation2}
presentlab <- fill.list(
  title = "Student presentations",
  topics = c("Student presentations"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "",
  hw_topics = c("No homework"),
  hw_duedate = ""
)
```

```{r}
edmlab <- fill.list(
  title = "EDM models",
  topics = c("Fitting EDM models"),
  pdf = "",
  rmd = "Labs/EDM Lab/EDM-Lab.Rmd",
  html = "Labs/EDM Lab/EDM-Lab.html",
  video = "",
  youtube = "",
  data = "",
  homework = "No Homework",
  key = "Labs/EDM Lab/EDM-Key.html",
  instructor = "Eli",
  hw_topics = c(""),
  hw_duedate = ""
)
```

```{r}
etsedmlab <- fill.list(
  title = "Forecasting with ETS models",
  topics = c("Forecasting with ETS models, Model comparison, Covariates in MARSS models"),
  pdf = "",
  rmd = "",
  html = c("https://atsa-es.github.io/atsa-labs/chap-msscov.html", "https://fish-forecast.github.io/Fish-Forecast-Webpage/Exp_Smoothing.html"),
  video = "",
  youtube = "",
  data = "",
  homework = "TBD",
  key = "",
  instructor = c("Eli"),
  hw_topics = c("Covariates in MARSS models"),
  hw_duedate = "Due next Thurs 11:59 PM PDT; email to instructor(s) for lab"
)
```

```{r}
perturblab <- fill.list(
  title = "Perturbation detection",
  topics = c("Perturbation detection"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
hierlab <- fill.list(
  title = "Hierarchical models",
  topics = c("Fitting hierarchical models"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
sslab1 <- fill.list(
  title = "Univariate state-space models",
  topics = c("Fitting univariate state-space models", "Animal movement", "TMB", "Bayesian"),
  pdf = "",
  rmd = "",
  html = "",
  youtube = "",
  video = "",
  data = "",
  homework = "HW #2",
  key = "",
  instructor = "Eli",
  hw_topics = c("Univariate state-space models"),
  hw_duedate = "Due Apr 25 Tues 11:59 PM PDT; post to GitHub"
)
```

```{r}
glmlab <- fill.list(
  title = "Generalized models",
  topics = c("Fitting models with non-Gaussian errors",
              "Fitting zero-inflated models"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
intlab <- fill.list(
  title = "Species interactions",
  topics = c("Fitting MARSS models for species interactions"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eli",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

