---
title: "2021 Schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

---

```{r child="list_of_labs.Rmd", include=FALSE}
```

```{r child="list_of_lectures.Rmd", include=FALSE}
```

```{r generate_dates, include=FALSE}
## first day of class
start_date <- as.Date("2023-03-28")
## all tues
tues <- seq.Date(from = start_date, by = 7, length.out = 10)
## all thur
thur <- tues + 2
## all qtr
qtr <- sort(c(tues, thur))
qtr <- sub("0(\\d)", "\\1", format(qtr, "%d %b"))
```

```{r weeks, include = FALSE}
week_lecs <- list(d1 = intro,
                   d2 = ts_basics,
                   d3 = arma_basics,
                   d4 = forecast, # lab
                   d7 = uni_ss,
                   d8 = marss, # lab
                   d5 = marss_covariates,
                   d12 = dfa, # lab
                   d10 = dlm,
                   d11 = HMMs, # lab
                   d13 = bayes,
                   d16 = bayes2, # project methods
                   d9 = model_inf,
                   d6 = freqdomain, # lab
                   d14 = spatial,
                   d18 = spatial2, # lab no hw
                   d17 = interactions1,
                   d15 = tbd,
                   d19 = present1,
                   d20 = present2
)
```

```{r week_labs, include = FALSE}
week_labs <- list(d1 = matrixlab,
                   d2 = lmlab,
                   d3 = "",
                   d4 = arimalab,
                   d5 = "",
                   d6 = sslab2,
                   d7 = "",
                   d8 = dfalab,
                   d9 = "",
                   d10 = hmmlab,
                   d11 = "",
                   d12 = bayeslab,
                   d13 = "",
                   d14 = freqdomainlab,
                   d15 = "",
                   d16 = spatiallab,
                   d17 = "",
                   d18 = helplab,
                   d19 = "",
                   d20 = presentlab
)
```

```{r lecture_topics2, include = FALSE}
lec_topics <- lapply(week_lecs, function(x){if(is.list(x)){x$topics}else{""}})
## topics formatted for html
lec_topics_html <- sapply(lapply(lec_topics, paste, "<br>", collapse=""), c)
names(lec_topics_html) <- NULL
```

```{r lab_topics2, include = FALSE}
lab_topics <- lapply(week_labs, function(x){if(is.list(x)){x$topics}else{""}})
## topics formatted for html
lab_topics_html <- sapply(lapply(lab_topics, paste, "<br>", collapse=""), c)
names(lab_topics_html) <- NULL
```

```{r hw_topics, include = FALSE}
hw_topics <- lapply(week_labs, function(x){if(is.list(x)){c(x$hw_topics,x$hw_duedate)}else{""}})
## topics formatted for html
hw_topics_html <- sapply(lapply(hw_topics, paste, "<br>", collapse=""), c)
names(hw_topics_html) <- NULL
```

```{r generate_syllabus, echo=FALSE}
## data frame with dates & topics
syl_txt <- data.frame(
  date = qtr,
  lec_topics = lec_topics_html,
  lab_topics = lab_topics_html,
  hw_topics = hw_topics_html
)
colnames(syl_txt) <- c("Date", "Lecture topics", "Lab topics", "Homework")
## generate table
kable(syl_txt, format = "html", caption = " ", escape = FALSE) %>%
  kable_styling(bootstrap_options = "striped",
                full_width = F,
                position = "left") %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "27em")
```

```{r echo=FALSE}
save(qtr, week_lecs, week_labs,  file="syllabus.RData")
```