---
title: "Final Project"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As part of the class, each student will have to write a complete, publishable (<20 page) paper using the time series analysis techniques learned in class. See below for details on the structure of the paper.

### Due Dates

* Project proposal due Fri April 21 11:59pm PST
* Project methods due Thurs May 11 11:59pm PST
* Final paper due Fri June 3th 11:59pm PST
* Presentations May 30 and June 2 during class time
* Peer review due Fri June 10th 11:59pm PST


# Data sets

Students are encouraged to use their own data and the paper may form a chapter for their thesis/dissertation. However some students might not have their own data. Students may also use data from the instructors, public datasets or datasets included in __R__ libraries.

Students without data or a particular project in mind should look at our [page of data sets](data_sets.html). You might also reach out to your advisor for data set suggestions.


# Project Plan

**due Fri April 21 11:59pm PST**

Write a 1-2 page description of your project idea that includes

* the question(s) of interest
* the data you will use
* your general approach to analyzing the data.

Things to consider:

* what type of time series models do you expect to use?
* univariate or multivariate
* one model or multiple models (and multi-model inference)
* covariates?
* linear, non-linear, or non-parametric
* Guassian or non-Gaussian

# Project Methods

**due Thurs May 11 11:59pm PST**

1. Write a draft methods section for your project. This is HW #5. The section should include a mathematical description of your model sufficient for someone else to understand and fit that model.

2. Show that you can fit a pilot version of your proposed model. In other words, show that you can fit your proposed model to some data.


# Preparation of final papers

**due Fri June 3th 11:59pm PST**

### Length

Final papers should be no more than 20 pages total, including all figures, tables and references. Please submit the PDF or Word version of your paper via email.

### Components

Each paper needs to have the following:

**Title page**: include the title, your name, and a "tweetable abstract" summarizing everything you've done in 140 characters or less. These won't be launched into the twitterverse, but as a concise (and exciting!) summary. 

**Abstract page**: Summarize briefly (ideally < 250 words) the novelty of your analysis, key results, and implications for future work

**Body / main text**: Please include an Introduction / Methods / Results / Discussion section. You're free to use any of the equations from the MARSS manual, or class material to provide equations, variables, descriptions, etc. 

**References**: Please use some kind of bibliography manager (like Endnote) to format all references consistently. 

**Figures / Tables**: Include figures and tables formatted for the journal of your choice. Examples you might want to include are: plots of your raw data, plots of underlying state estimates, plots of future projections, tables of parameter estimates, model selection (AICc) etc. 

### Style

As long as you include page numbers and line numbers, you are free to use the general formatting guidelines for whichever journal you plan to eventually submit your paper to. For some examples, see 

CJFAS: http://www.nrcresearchpress.com/

Ecology: http://esapubs.org/esapubs/preparation.htm

Journal of Applied Ecology: http://www.journalofappliedecology.org/view/0/authorGuideline.html

# Peer reviews

## Advice on reviewing scientific papers

If you are looking for some guidance on writing reviews of scientific papers, here are some links to various columns, blogs, etc, about reviewing scientific papers:

[Arthropod Ecology](http://arthropodecology.com/2012/02/29/how-to-review-a-scientific-paper/)
[Violent metaphors](http://violentmetaphors.com/2013/12/13/how-to-become-good-at-peer-review-a-guide-for-young-scientists/) (don't let the name scare you)
[Duke Writing Lab](http://twp.duke.edu/uploads/media_items/scientificarticlereview.original.pdf)
[Examples of good reviews from Peerage](http://www.peerageofscience.org/review/review-examples/)

## Guidelines

Final papers will be peer-reviewed and reviewed by instructors based on the following criteria.

[Example of a manuscript review for Fish 507.docx](Files/MANUSCRIPT REVIEW FOR FISH 507.docx)

[Review Template.docx](Files/review_template.docx)

[Review Template.Rmd](Files/review_template.Rmd)

