---
title: "List of Lectures"
output: html_document
---

<!-- week_lecs is defined in asyllabus.Rmd -->

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
intro <- list(
  title = "Intro to time series analysis",
  topics = c("Course overview",
             "Properties of time series",
             "Data transformations",
             "Time series decomposition"),
  pdf = c("Lectures/Week 1/lec_00_class_overview.pdf", "Lectures/Week 1/lec_01_intro_to_ts.pdf"),
  ppt = "",
  rmd = c("Lectures/Week 1/lec_00_class_overview.Rmd", "Lectures/Week 1/lec_01_intro_to_ts.Rmd"),
  html = c("Lectures/Week 1/lec_00_class_overview.html", "Lectures/Week 1/lec_01_intro_to_ts.html"),
  video = "https://youtu.be/XeAN-zYhqGw",
  youtube = "",
  reading = c("[CM09: Chap 1](Files/Introductory_Time_Series_With_R.pdf)", "[HA18: Chap 6](https://otexts.org/fpp2/decomposition.html)","[HSW18: Intro to ts](https://nwfsc-timeseries.github.io/atsa-labs/chap-ts.html)" ),
  instructor = "Mark"
)
```

```{r}
ts_basics <- list(
  title = "Stationarity & introductory functions",
  topics = c("Covariance & correlation",
             "Autocorrelation & Partial autocorrelation",
             "Cross correlation",
             "White noise",
             "Random walks",
             "Differencing"),
  pdf = "Lectures/Week 1/lec_02_covariance_stationarity.pdf",
  ppt = "",
  rmd = "Lectures/Week 1/lec_02_covariance_stationarity.Rmd",
  html = "Lectures/Week 1/lec_02_covariance_stationarity.html",
  video = "https://youtu.be/vwHqxe9eVMk",
  youtube = "",
  reading = c("[CM09: Chap 2](Files/Introductory_Time_Series_With_R.pdf)","[CM09: Chap 4](Files/Introductory_Time_Series_With_R.pdf)","[HA18: Chap 8.1](https://otexts.org/fpp2/stationarity.html)","[HSW18: Intro to ts](https://nwfsc-timeseries.github.io/atsa-labs/chap-ts.html)"),
  instructor = "Mark"
)
```

```{r}
arma_basics <- list(
  title = "Intro to ARMA models",
  topics = c("Autoregressive (AR) models",
             "Moving average (MA) models",
             "Stationary AR models",
             "Invertible MA models",
             "Using ACF & PACF for model ID"),
  pdf = "Lectures/Week 2/lec_03_ARMA_models.pdf",
  ppt = "",
  rmd = "Lectures/Week 2/lec_03_ARMA_models.Rmd",
  html = "Lectures/Week 2/lec_03_ARMA_models.html",
  video = "https://youtu.be/IgX9Bpu3ggc",
  youtube = "",
  reading = c("[CM09: Chap 6](Files/Introductory_Time_Series_With_R.pdf)","[CM09: Chap 7](Files/Introductory_Time_Series_With_R.pdf)","[HA18: Chap 8.1-8.5](https://otexts.org/fpp2/arima.html)"),
  instructor = "Mark"
)
```


```{r}
forecast <- list(
  title = "Box-Jenkins Method",
  topics = c("Box-Jenkins method", "Fitting ARIMA models with R", "Forecasting with ARIMA models", "Seasonal ARIMA models"),
  pdf = c("Lectures/Week 2/lec_04_Fitting_and_Selecting_ARMA_models.pdf", "Lectures/Week 2/lec_04_Forecasting_ARIMA.pdf", "Lectures/Week 2/lec_04_Arima_intercepts.pdf"),
  ppt = "",
  rmd = c("Lectures/Week 2/lec_04_Fitting_and_Selecting_ARMA_models.Rmd", "Lectures/Week 2/lec_04_Forecasting_ARIMA.Rmd", "Lectures/Week 2/lec_04_Arima_intercepts.Rmd", "Lectures/Week 3/lec_05_box_jenkins_part2.Rmd"),
  html = c("Lectures/Week 2/lec_04_Fitting_and_Selecting_ARMA_models.html", "Lectures/Week 2/lec_04_Forecasting_ARIMA.html", "Lectures/Week 2/lec_04_Arima_intercepts.html", "Lectures/Week 3/lec_05_box_jenkins_part2.html"),
  video = c("https://youtu.be/ML1l4Zk_5Vo", "https://youtu.be/HOVDmx_juMk"),
  youtube = "",
  reading = c("[HA18: Chap 8.6-8.9](https://otexts.org/fpp2/arima.html)","[H18: ARIMA Models](https://fish-forecast.github.io/Fish-Forecast-Bookdown/3-arima-models.html)"),
  instructor = "Eli"
)
```


```{r}
freqdomain <- list(
  title = "Frequency domain methods",
  topics = c("Frequency domain",
             "Fourier transforms",
             "Spectral analysis",
             "Wavelet analysis"),
  pdf = "Lectures/Week 8/lec_16_freq_domain.pdf",
  ppt = "",
  rmd = "Lectures/Week 8/lec_16_freq_domain.Rmd",
  html = "Lectures/Week 8/lec_16_freq_domain.html",
  video = "https://youtu.be/XCnHQve-Tmk",
  youtube = "",
  reading = c("[Graps (1995)](https://www.eecis.udel.edu/~amer/CISC651/IEEEwavelet.pdf)", "[Percival & Walden (2000)](https://staff.washington.edu/dbp/wmtsa.html)"),
  instructor = "Mark"
)
```

```{r}
uni_ss <- list(
  title = "Univariate state-space models",
  topics = c("Univariate state-space models"),
  pdf = "",
  ppt = "",
  rmd = c("Lectures/Week 3/lec_05_univariate_state_space.Rmd"),
  html = c("Lectures/Week 3/lec_05_univariate_state_space.html"),
  video = "https://youtu.be/-G_ejXMzEWw",
  youtube = "",
  reading = c("[HWS18a: Chap 7](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)",
              "[HWSb: Chap 6](https://nwfsc-timeseries.github.io/atsa-labs/chap-univariate-state-space.html)",
              "[MARSS function](Lectures/Week 3/MARSS_function.html)","[MARSS Ref Sheet](Lectures/Week 3/MARSS_Reference_Sheet.pdf)", "[uni_example_1.R](Lectures/Week 3/univariate_example_1.R)",
              "[uni_example_2.R](Lectures/Week 3/univariate_example_2.R)",
              "[uni_example_3.R](Lectures/Week 3/univariate_example_3.R)",
              "[uni_example_4.R](Lectures/Week 3/univariate_example_4.R)"),
  instructor = "Eli"
)
```

```{r}
marss <- list(
  title = "Multivariate state-space models",
  topics = c("Introduction to multivariate state-space models"),
  pdf = c("Lectures/Week 3/lec_05b_univariate_state_space_part2.pdf", "Lectures/Week 3/lec_06_marss.pdf"),
  ppt = "Lectures/Week 3/lec_06_marss.ppt",
  rmd = c("Lectures/Week 3/lec_05b_univariate_state_space_part2.Rmd"),
  html = c("Lectures/Week 3/lec_05b_univariate_state_space_part2.html"),
  video = "https://youtu.be/4nrZZGMY1bc",
  youtube = "",
  reading = c("[HWS18a: Chap 8](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)",
              "[MARSS function](Lectures/Week 3/MARSS_function.html)",
              "[MARSS Ref Sheet](Lectures/Week 3/MARSS_Reference_Sheet.pdf)",
              "[uni_example_0.R](Lectures/Week 3/univariate_example_0.R)",
              "[marss_example_0.R](Lectures/Week 3/marss_example_0.R)",
              "[marss_example_0_with_comments.R](Lectures/Week 3/marss_example_0_with_comments.R)",
              "[marss_example_1.R](Lectures/Week 3/marss_example_1.R)",
              "[marss_example_2.R](Lectures/Week 3/marss_example_2.R)",
              "[marss_example_3.R](Lectures/Week 3/marss_example_3.R)",
              "[marss_example_4.R](Lectures/Week 3/marss_example_4.R)",
              "[marss_example_5.R](Lectures/Week 3/marss_example_5.R)"),
  instructor = "Eli"
)
```

```{r}
marss_covariates <- list(
  title = "Covariates in MARSS models",
  topics = c("MARSSX and ARMAX models",
             "Seasonal effects",
             "Missing covariates"),
  pdf = c("Lectures/Week 4/lec_07_covariates.pdf"),
  ppt = "",
  rmd = c("Lectures/Week 4/lec_07_covariates.Rmd"),
  html = c("Lectures/Week 4/lec_07_covariates.html"),
  video = "https://youtu.be/2Jb5pzgtuH0",
  youtube = "",
  reading = c(
    "[lec_07_covariates.R](Lectures/Week 4/lec_07_covariates.R)",
    "[MARSS Models HWS18a: Chap 8](https://nwfsc-timeseries.github.io/atsa-labs/chap-msscov.html)",
    "[Missing Covariates HWS18a: Chap 11](https://nwfsc-timeseries.github.io/atsa-labs/chap-mssmiss.html)",
    "[HA18: Chap 5](https://otexts.com/fpp2/regression.html)",
    "[HA18: Chap 9](https://otexts.com/fpp2/dynamic.html)", 
    "[H18: Chap 6](https://fish-forecast.github.io/Fish-Forecast-Bookdown/6-1-multivariate-linear-regression.html)"),
  instructor = "Eli"
)
```
```{r}
covariates <- list(
  title = "Covariates in time-series models",
  topics = c("Including covariates (predictors) in models",
             "Seasonal effects",
             "Missing covariates",
             "Colinearity", "MARSSX and ARMAX"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  reading = "",
  #reading = c("[HA18: Chap 5](https://otexts.com/fpp2/regression.html)","[HA18: Chap 9](https://otexts.com/fpp2/dynamic.html)", "[H18: Chap 6](https://fish-forecast.github.io/Fish-Forecast-Bookdown/6-1-multivariate-linear-regression.html)"),
  instructor = "Eli"
)
```

```{r}
model_inf <- list(
  title = "Multi-model inference",
  topics = c("Multi-model inference and selection",
             "Information criteria",
             "Cross-validation & LOOIC"),
  pdf = "Lectures/Week 7/lec_13_modelselection.pdf",
  ppt = "",
  rmd = "Lectures/Week 7/lec_13_modelselection.Rmd",
  html = "Lectures/Week 7/lec_13_modelselection.html",
  video = "https://youtu.be/Z-kIEMqGD-c",
  youtube = "",
  reading = c("See list of references in the lecture", "[HA18: Section 3.4](https://otexts.com/fpp2/accuracy.html)", "[H18: Forecast accuracy](https://fish-forecast.github.io/Fish-Forecast-Bookdown/5-perf-testing.html)","[H18: Variable selection](https://fish-forecast.github.io/Fish-Forecast-Bookdown/6-1-multivariate-linear-regression.html)"),
  instructor = "Eric"
)
```

```{r}
dlm <- list(
  title = "Dynamic Linear Models",
  topics = c("Dynamic linear models (DLMs)"),
  pdf = "Lectures/Week 5/lec_09_intro_to_DLMs.pdf",
  ppt = "",
  rmd = "Lectures/Week 5/lec_09_intro_to_DLMs.Rmd",
  html = "Lectures/Week 5/lec_09_intro_to_DLMs.html",
  video = "https://youtu.be/Uxx2jK7heNE",
  youtube = "",
  reading = c("Petris et al. (2009)", "[HWS18a: Chap 16](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)", "Scheuerell & Williams (2005)"),
  instructor = "Mark"
)
```

```{r}
dlm2 <- list(
  title = "Multivariate dynamic linear models",
  topics = c("Multivariate dynamic linear models (DLMs)"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  reading = c(""),
  youtube = "",
  instructor = "Mark"
)
```

```{r}
dfa <- list(
  title = "Dynamic Factor Analysis",
  topics = c("Regression with autocorrelated errors", "Dynamic factor analysis (DFA)"),
  pdf = "Lectures/Week 4/lec_08_intro_to_DFA.pdf",
  ppt = "",
  rmd = "Lectures/Week 4/lec_08_intro_to_DFA.Rmd",
  html = "Lectures/Week 4/lec_08_intro_to_DFA.html",
  video = "https://youtu.be/LVlo8I0PdPA",
  youtube = "",
  reading = c("[Zuur et al. 2003a](http://www.nrcresearchpress.com/doi/abs/10.1139/f03-030#.XFyd_xJ7l9M)", "[Zuur et al. 2003b](https://onlinelibrary.wiley.com/doi/abs/10.1002/env.611)", "[Ohlberger et al. 2016](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.1333)", "[HWS18a: Chap 10](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)"),
  instructor = "Mark"
)
```

```{r}
bayes <- list(
  title = "Bayesian estimation: univariate models",
  topics = c("Bayesian estimation of time-series and state-space models","Stan"),
  ppt = "",
  pdf = "Lectures/Week 6/lec_11_bayes.pdf",
  rmd = "Lectures/Week 6/lec_11_bayes.Rmd",
  html = "Lectures/Week 6/lec_11_bayes.html",
  video = "https://youtu.be/PzMFjO1sjEo",
  youtube = "",
  reading = c("[Stan manual](https://mc-stan.org/users/documentation/)", "[Monnahan et al. 2017](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12681)", "[mcmc intro](https://livefreeordichotomize.com/2017/10/14/mcmc-and-the-case-of-the-spilled-seeds/)"),
  instructor = "Eric"
)
```

```{r}
bayes2 <- list(
  title = "Bayesian estimation: multivariate models",
  topics = c("MAP estimation", "Multivariate models", "DFA", "Writing Bayesian models in Stan"),
  pdf = "Lectures/Week 6/lec_12_bayes2.pdf",
  ppt = "",
  rmd = "Lectures/Week 6/lec_12_bayes2.Rmd",
  html = "Lectures/Week 6/lec_12_bayes2.html",
  video = "https://youtu.be/ZO_S7uo_nVg",
  youtube = "",
  reading = "[Stan manual](https://mc-stan.org/users/documentation/)",
  instructor = "Eric"
)
```

```{r}
glm <- list(
  title = "Generalized TS models",
  topics = c("Time series models with non-Gaussian errors",
             "Non-normal response variables"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  reading = c(""),
  youtube = "",
  instructor = "Eric"
)
```

```{r}
spat_cor <- list(
  title = "Spatial correlation",
  topics = c("Time series models with spatial autocorrelation"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  reading = "",
  #reading = c("[GitHub Lec 18 Files](https://github.com/nwfsc-timeseries/atsa/tree/master/Lectures/Week%209)"),
  instructor = "Eric"
)
```

```{r}
ets <- list(
  title = "Exponential smoothing models",
  topics = c("Exponential smoothing models (ETS)", "Crossvalidation tests", "Forecasting with ETS models"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  reading = "",
  #reading = c("[HA18: Chap 7](https://otexts.com/fpp2/expsmooth.html)","[H18: Chap 4](https://fish-forecast.github.io/Fish-Forecast-Bookdown/4-exponential-smoothing-models.html)"),
  instructor = "Eli"
)
```

```{r}
interactions1 <- list(
  title = "B Matrix",
  topics = c("AR(p) Models", "Estimating interaction strengths",
             "Gompertz models", "Stability metrics"),
  pdf = "",
  ppt = "",
  rmd = "Lectures/Week 9/Old interactions lectures/Lec_16/Lec_16.Rmd",
  html = "Lectures/Week 9/Old interactions lectures/Lec_16/Lec_16.html",
  video = "https://youtu.be/p06tdo9JyWk",
  youtube = "",
  reading = c("[Hampton et al 2013](https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1890/13-0996.1)","[Ives et al 2003](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/0012-9615%282003%29073%5B0301%3AECSAEI%5D2.0.CO%3B2)","[HWS18a: Chap 14 & 18](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)", "[MAR Stability Metrics](https://github.com/mdscheuerell/marstab/blob/master/mar_stab_properties_text.pdf)","[AR(1) errors](https://nwfsc-timeseries.github.io/atsa-labs/chap-noisy-sensors-.html)", "[Mark's B estimation talk](https://github.com/mdscheuerell/mar_sims/blob/master/presentation/open_sci_summit_2020.pdf)"),
  instructor = "Eli"
)
```

```{r}
spatial <- list(
  title = "Spatial and spatio-temporal models I",
  topics = c("Spatial and spatio-temporal models"),
  pdf = c(""),
  ppt = "",
  rmd = c("Lectures/Week 9/lec_17_spatiotemporal.Rmd"),
  html = c("Lectures/Week 9/lec_17_spatiotemporal.html"),
  video = "https://youtu.be/i6YxN8qbrfg",
  youtube = "",
  reading = c("[River spatial models](https://onlinelibrary.wiley.com/doi/pdf/10.1111/ele.12084)", "[River spatial 2](https://www.researchgate.net/profile/Jay-Ver-Hoef/publication/227369314_A_Moving_Average_Approach_for_Spatial_Statistical_Models_of_Stream_Networks/links/5f9820d6299bf1b53e49aa00/A-Moving-Average-Approach-for-Spatial-Statistical-Models-of-Stream-Networks.pdf)", "[River spatial 3](https://www.fs.fed.us/rm/pubs_other/rmrs_2014_issak_d001.pdf)"),
  #reading = c("[GitHub folder with code](https://github.com/nwfsc-timeseries/atsa/tree/master/Lectures/Week%209)"),
  instructor = "Eric"
)
```

```{r}
spatial2 <- list(
  title = "Spatial and spatio-temporal models II",
  topics = c("Spatial and spatio-temporal models"),
  pdf = "",
  ppt = "",
  rmd = c("Lectures/Week 9/lec_18_spatiotemporal.Rmd"),
  html = c("Lectures/Week 9/lec_18_spatiotemporal.html"),
  video = "https://youtu.be/qalgyHoLumg",
  youtube = "",
  reading = c(""),
  instructor = "Eric"
)
```

```{r}
HMMs <- list(
  title = "Hidden Markov models",
  topics = c("Hidden Markov models"),
  pdf = "",
  ppt = "",
  rmd = "Lectures/Week 5/lec_10_hmm.Rmd",
  html = "Lectures/Week 5/lec_10_hmm.html",
  video = "https://youtu.be/CqmAs3aPf_k",
  youtube = "",
  reading = c("[Zucchini et al. 2006](https://www.researchgate.net/profile/Jan_Bulla/publication/256503512_Hidden_Markov_Models/links/0c9605232dce693fa3000000/Hidden-Markov-Models.pdf)", "[depmixS4 vignette](https://cran.r-project.org/web/packages/depmixS4/vignettes/depmixS4.pdf)"),
  instructor = "Eric"
)
```

```{r}
regvsss <- list(
  title = "Regression versus State Space",
  topics = c("Regression versus State Space"),
  pdf = "",
  ppt = "",
  rmd = c("Lectures/Week 9/reg_vs_SS.Rmd"),
  html = c("Lectures/Week 9/reg_vs_SS.html"),
  video = "https://youtu.be/m8_RRHODC6A",
  youtube = "",
  reading = c(""),
  instructor = "Eli"
)
```

```{r}
present1 <- list(
  title = "Student presentations",
  topics = c("Student presentations"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  reading = c(""),
  youtube = "",
  instructor = ""
)
```

```{r}
present2 <- list(
  title = "Student presentations",
  topics = c( "Student presentations"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  reading = c(""),
  youtube = "",
  instructor = ""
)
```

```{r}
EDM <- list(
  title = "Semi- and non-parametric models",
  topics = c("Semi- and non-parametric models"),
  pdf = "Lectures/Week 8/lec_15_semiparametric.pdf",
  ppt = "",
  rmd = "Lectures/Week 8/lec_15_semiparametric.Rmd",
  html = "Lectures/Week 8/lec_15_semiparametric.html",
  video = "https://youtu.be/LN1XsC8DKPg",
  youtube = "",
  reading = c("[Chang et al. 2017](https://link.springer.com/epdf/10.1007/s11284-017-1469-9?shared_access_token=uo6dSpx2HhqFSdKklUb91ve4RwlQNchNByi7wbcMAY46qf1ru5YtibpRTA9bGJJXdv8wOCFEurjER4XMpGuPd-QPKglrjNFUFLLw1xY5KfAWa2Ln-vHCv747UBEe-04n2oRgCUyZ0dONF9fk2aRo8j07QNwfnwGIhi71df0wnXA%3D)", "[Sugihara and May](https://www.nature.com/articles/344734a0)", "[rEDM Vignette](https://cran.r-project.org/web/packages/rEDM/vignettes/rEDM-tutorial.html)","[Intro to EDM, video](https://www.youtube.com/watch?v=fevurdpiRYg)","[EDM lecture](https://www.youtube.com/watch?v=6yq0VAriUIQ)", "[EDM for beginners, review](https://link.springer.com/article/10.1007/s11284-017-1469-9)"),
  instructor = "Eric"
)
```

```{r}
zeros <- list(
  title = "Zero-inflated data",
  topics = c("Zero-inflated data","Perturbation analysis","outliers","standardized residuals"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  reading = "",
  #reading = c("[O'hara and Kotze 2010](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2010.00021.x)","[Ekwaru et al. 2017](https://amstat.tandfonline.com/doi/abs/10.1080/19466315.2017.1369900?journalCode=usbr20#.XIe-RBNKiM4)","[HWS18a: Chap 12](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)"),
  instructor = "Eric"
)
```

```{r perturb_lec}
perturb <- list(
  title = "Perturbations and outliers",
  topics = c("Perturbations","interventions","outliers","standardized residuals"),
  pdf = "",
  ppt = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  reading = "",
  #reading = "[HWS18a: Chap 12](https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf)",
  instructor = "Eric/Eli"
)
```
