---
title: "List of Labs"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# you can vector c() of things; pdf, rmd, video, data, key should be links
```

```{r}
matrixlab <- list(
  title = "Matrix math in R",
  topics = c("Matrices & matrix algebra","(review on your own)"),
  pdf = "Labs/Week 0 basic matrix/basic-matrix-math.pdf",
  rmd = "",
  html = "https://nwfsc-timeseries.github.io/atsa-labs/chap-basicmat.html",
  video = "",
  youtube = "",
  data = "",
  homework = "Optional (not part of grade): Listed at end of <a href='https://nwfsc-timeseries.github.io/atsa-labs/chap-basicmat.html'>Chapter 1</a> in the ATSA lab book.",
  key = "Labs/Week 0 basic matrix/basic-matrix-math-key.pdf",
  instructor = "",
  hw_topics = "Review of matrix math",
  hw_duedate = "Optional"
)
```

```{r}
lmlab <- list(
  title = "Writing models in matrix form",
  topics = c("Writing models in matrix form (through section 2.5)",
               "Basic time series functions",
               "Autocorrelation"),
  pdf = "",
  rmd = "",
  html = c("https://nwfsc-timeseries.github.io/atsa-labs/chap-mlr.html","https://nwfsc-timeseries.github.io/atsa-labs/chap-ts.html"),
  video = c(""),
  youtube = "",
  data = "",
  homework = "Optional (but important to understand course material): End of <a href='https://nwfsc-timeseries.github.io/atsa-labs/chap-mlr.html'>Chapter 2</a> in the ATSA lab book.",
  key = "Labs/Week 1/HW_1_Key.html",
  instructor = c("Eli/Mark"),
  hw_topics = c("linear regression in matrix form"),
  hw_duedate = "Optional"
)
```

```{r}
forecastlab <- list(
  title = "Box-Jenkins Methods",
  topics = c("Simulating ARMA models", "Fitting ARIMA models", "Forecasting with ARIMA models","Box-Jenkins Methods"),
  pdf = "",
  rmd = "",
  html = c("https://nwfsc-timeseries.github.io/atsa-labs/chap-tslab.html", "https://nwfsc-timeseries.github.io/atsa-labs/chap-boxjenkins-.html"),
  video = "",
  youtube = "",
  data = "",
  homework = "Intro to ts: problems at end of <a href='https://nwfsc-timeseries.github.io/atsa-labs/chap-tslab.html'>Chapter 4</a> in the ATSA lab book.<br>Fitting ARMA models: problems at end of <a href='https://nwfsc-timeseries.github.io/atsa-labs/chap-boxjenkins-.html'>Chapter 5</a> in the ATSA lab book.",
  key = c("Labs/Week 2/HW_2_ts_Key.html","Labs/Week 2/HW_2_box-jenkins_Key.html"),
  instructor = "Mark & Eli",
  hw_topics = c("ARIMA models"),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to instructor(s) for lab"
)
```

```{r}
sslab1 <- list(
  title = "Univariate state-space models",
  topics = c("Simulating ARMA models", "Fitting arima models", "Fitting univariate state-space models"),
  pdf = "",
  rmd = "",
  html = "",
  youtube = "",
  video = "",
  data = "",
  homework = "Intro to uniSS: problems at end of chapter; Due 11:49 pm next Thurs",
  key = "",
  instructor = "Eli",
  hw_topics = c("Univariate state-space models"),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to instructor(s) for lab"
)
```

```{r}
sslab2 <- list(
  title = "State-space models",
  topics = c("Fitting univariate and mulitvariate state-space models"),
  pdf = "",
  rmd = "",
  html = c("https://nwfsc-timeseries.github.io/atsa-labs/chap-univariate-state-space.html", "https://nwfsc-timeseries.github.io/atsa-labs/chap-mss.html"),
  video = "",
  youtube = "",
  data = "",
  homework = "HW #2 questions and data: [Rmd](https://nwfsc-timeseries.github.io/atsa/Labs/Week 3/NO2Lab/HW2-NO2.Rmd), [html](https://nwfsc-timeseries.github.io/atsa/Labs/Week 3/NO2Lab/HW2-NO2.html), [data](https://nwfsc-timeseries.github.io/atsa/Labs/Week 3/NO2Lab/ECNNO2.RData),
  [Tips](https://nwfsc-timeseries.github.io/atsa/Labs/Week 3/NO2Lab/HW2-Tips.html)",
  key = c("Labs/Week 3/NO2Lab/HW2-NO2-Key.html"),
  instructor = "Eli",
  hw_topics = c("State-space models"),
  hw_duedate = "Due Sat Jan 30 11:59 PM PST; email to Eli"
)
```

```{r}
dfalab <- list(
  title = "DFA models",
  topics = c("Fitting DFA models"),
  pdf = "",
  rmd = "",
  html = "Labs/Week 4/intro-to-dfa.html",
  video = "",
  youtube = "",
  data = "",
  homework = "HW #3 Problems at end of Chap 10 of Lab Book",
  key = "Labs/Week 4/HW_4_answer_key.pdf",
  instructor = "Mark",
  hw_topics = c("Dynamic Factor Analysis"),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to Mark"
)
```

```{r}
edmlab <- list(
  title = "EDM models",
  topics = c("Fitting EDM models"),
  pdf = "",
  rmd = "Labs/EDM Lab/EDM-Lab.Rmd",
  html = "Labs/EDM Lab/EDM-Lab.html",
  video = "",
  youtube = "",
  data = "",
  homework = "No Homework",
  key = "Labs/EDM Lab/EDM-Key.html",
  instructor = "Eli",
  hw_topics = c(""),
  hw_duedate = ""
)
```

```{r}
dlmlab <- list(
  title = "Dynamic Linear Models",
  topics = c("Fitting DLMs"),
  pdf = "",
  rmd = "Labs/Week 5/intro-to-dlms.Rmd",
  html = "Labs/Week 5/intro-to-dlms.html",
  video = "https://youtu.be/KpBgTqcsqNg",
  youtube = "",
  data = "",
  homework = "HW #4 Problems at end of Chap 9 in lab book",
  key = "Labs/Week 5/HW_5_answer_key.pdf",
  instructor = "Mark",
  hw_topics = c("Dynamic Linear Models"),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to instructor(s) for lab"
)
```

```{r}
etsedmlab <- list(
  title = "Forecasting with ETS models",
  topics = c("Forecasting with ETS models, Model comparison, Covariates in MARSS models"),
  pdf = "",
  rmd = "",
  html = c("https://nwfsc-timeseries.github.io/atsa-labs/chap-msscov.html", "https://fish-forecast.github.io/Fish-Forecast-Webpage/Exp_Smoothing.html"),
  video = "",
  youtube = "",
  data = "",
  homework = "TBD",
  key = "",
  instructor = c("Eli"),
  hw_topics = c("Covariates in MARSS models"),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to instructor(s) for lab"
)
```

```{r bayeslab}
bayeslab <- list(
  title = "Fitting models with STAN",
  topics = c("Bayesian estimation", "STAN"),
  pdf = "",
  rmd = "https://nwfsc-timeseries.github.io/atsa-labs/Rmds/fitting-models-with-stan.Rmd",
  html = "https://nwfsc-timeseries.github.io/atsa-labs/chap-stan.html",
  video = "",
  youtube = "",
  data = "",
  homework = "HW # 5. Project Methods",
  key = "",
  instructor = "Eric",
  hw_topics = c(""),
  hw_duedate = "Due next Thurs 11:59 PM PST; email to all instructors"
)
```

```{r hmmlab}
hmmlab <- list(
  title = "B Estimation Discussion",
  topics = c("Interactions", "Stability", "B matrix"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "HW #6: HMM/Bayesian State space models. [Rmd](https://nwfsc-timeseries.github.io/atsa/Labs/HW6/HW6.Rmd), [html](https://nwfsc-timeseries.github.io/atsa/Labs/HW6/HW6.html), [Rmd Part 2 JAGS](https://nwfsc-timeseries.github.io/atsa/Labs/HW6/HW6-part2-JAGS.Rmd), [Part 2 Online](https://rstudio.cloud/project/2228346)",
  key = c("Labs/HW6/HW6-key-part1.html", "Labs/HW6/HW6-key-part2.html"),
  instructor = "Eli & Eric",
  hw_topics = c(""),
  hw_duedate = "Due Monday Mar 1 11:59 PM PST; email to Eric & Eli"
)
```


```{r}
glmlab <- list(
  title = "Generalized models",
  topics = c("Fitting models with non-Gaussian errors",
              "Fitting zero-inflated models"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
intlab <- list(
  title = "Species interactions",
  topics = c("Fitting MARSS models for species interactions"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eli",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
perturblab <- list(
  title = "Perturbation detection",
  topics = c("Perturbation detection"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
hierlab <- list(
  title = "Hierarchical models",
  topics = c("Fitting hierarchical models"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Eric",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```


```{r}
freqdomainlab <- list(
  title = "Frequency Domain",
  topics = c("Frequency domain methods", "wavelet analysis", "Stochastic volatility"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "Mark",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

```{r}
spatiallab <- list(
  title = "Spatio-temporal models",
  topics = c("Spatio-temporal models"),
  pdf = "",
  rmd = "Labs/Week 9/lab.Rmd",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework; Datasets for in class lab  [Data1](Labs/Week 9/SNOTEL_metadata.csv), [Data2](Labs/Week 9/SNOTEL_Washington_1981_2013.csv), [Data3](Labs/Week 9/tck_longform.Rdata)",
  key = "",
  instructor = "Eric",
  hw_topics = c(""),
  hw_duedate = "work on projects"
)
```


```{r studentpresentation2}
presentlab <- list(
  title = "Student presentations",
  topics = c("Student presentations"),
  pdf = "",
  rmd = "",
  html = "",
  video = "",
  youtube = "",
  data = "",
  homework = "No homework",
  key = "",
  instructor = "",
  hw_topics = c("No homework"),
  hw_duedate = "work on projects"
)
```

