---
title: "Student Projects"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here are the independent projects from students who took the class in prior years.

# Presentation topics

Here are the topics of the students' final projects from years past.

### 2023

* "Puget Sound river nutrients through time– Detecting decades of water quality change using
dynamic factor analysis"
* "Modeling forty years of dissolved oxygen in the Middle Green River: Examining trends from 1980 to 2022"
* "Modeling mountain lion movement and space use with multivariate autoregressive models" 
* "Hidden Markov model identifies critical changepoint in the pre-bloom dynamics of an algal
bloom microbiome"
* "Searching for causal mechanisms relating to the decline in repeat spawning rates of steelhead using time series of data for Olympic Peninsula steelhead"
* "Quantifying long term trends of pinniped species across multiple spatial scales"
* "Divided or united? Delving into Bering Sea Tanner crab (Chionoecetes bairdi) management districts"
* "An Applied Time Series Model of an Ocean Microbiome Response to an Algal Bloom Ecosystem Disturbance"
* "Applying Hidden Markov Models to timeseries of seabird densities"

### 2021

* "Heat-Related Mortality in the Greater Seattle Area (1980 - 2018)"
* "Modeling spatio-temporal dynamics of mountain pine beetle activity in the Southern Rockies"
* "Quantifying the success of invasive green sunfish eradication from McGee Wash, Arizona"
* "Recovery of the California brown pelican following DDT contamination in the Southern California Bight"
* "Mobile technologies reveal human activity across urban lakes"
* "Population viability analysis of marbled murrelets reveal long-term decline in the Salish Sea"
* "Using removal data to estimate rusty crayfish population growth and spread in the John Day River"
* "Synchronous dynamics in marine fishes in the Southern California Bight"

### 2019

* "A century of stable isotope data demonstrates robust trophic ecology and ecosystem productivity from archival bone of a generalist predator"
* "Estimating common trends in bull trout life history strategies"
* "Assessing spatial covariance among time series of river discharge across western North America"
* "Timing and abundance of juvenile spring Chinook emigrants from the Chiwawa River"
* "Cetacean Strandings in the Pacific Northwest"

### 2017

* "Trends and shortcomings in midwinter waterfowl surveys along the Pacific Flyway: a multivariate state-space modeling approach"
* "Cyclic dominance of alternative male phenotypes in an introduced sockeye salmon population"
* "An application of arima model to study the association between particulate matters and hospital admission for respiratory disease"
* "Time resolved exposures of mice to cadmium: hair as a biomarker of exposure"
* "Characterizing temporal variability in pelagic communities for biological monitoring at marine renewable energy sites"
* "Lake size and watershed characteristics mediate the effect of climate on lake water levels in the Puget Sound Lowlands"
* "Determining multi-scale controls on river temperature: a time series approach"

### 2015

* "Modeling domoic acid in Pacific razor clams (_Siliqua patula_) at Long Beach, WA, USA using autoregressive integrated moving average and generalized linear models"
* "Synthesis of Bristol Bay sockeye salmon genetic data improves understanding of migration patterns to inform commercial fisheries management"
* "Behavior of depth selection in lake trout (_Salvelinus namaycush_) morphotypes in northern Lake Superior"
* "Extracting time-varying climate-driven growth index for use in stock assessment models"
* "A comparison of statistical models applicable for environmental assessments of marine renewable energy sites"
* "A method of reconstructing the daily growth of large wildfires with state space models"
* "Modeling and forecasting multispecies catches in the Uruguayan longline fishery"
* "Chinook salmon jack rate in the Columbia River basin: are jacks trending?"
* "Spatial asynchrony in juvenile sockeye salmon growth driven by competition in a changing climate"

### 2013

* "Can distinct sub-populations within the Prince William Sound be classified by differing responses in male fecundity and do oceanographic conditions affect surveys of male fecundity?"
* "Scales of variability in forage fish stocks"
* "Extreme weather incidents and prey availability affect Magellanic penguin (Spheniscus magellanicus) reproductive success"
* "Environment drives changes in recruitment for most marine fisheries"
* "Initial exploration of modeling options for an environmental driver of sardine abundance"
* "Demographic structure of Puget Sound Pacific herring stocks"
* "Common trends in spawning stock biomass of northeast pacific marine stocks"
* "Describing variability of fish and macrozooplankton density at marine hydrokinetic energy sites"
* "Lake specific variation in juvenile sockeye salmon growth driven by competition in a changing climate"
* "Environmental and phenological variability: match-mismatch effects of lake conditions and entry timing on sockeye salmon survival and growth"

# Publications

Siple, M. C. and Francis, T. B. 2016. Population diversity in Pacific herring of Puget Sound, USA. Oecologia 180: 111-125.[Link to article](https://doi.org/10.1007/s00442-015-3439-7)

Linder, H.L., Horne, J.K. and E.J. Ward. 2017. Modeling baseline conditions of ecological indicators: Marine renewable energy environmental monitoring,
Ecological Indicators, Volume 83: 178-191 [Link to article](https://doi.org/10.1016/j.ecolind.2017.07.015)

Gonzalez, S., Horne, J. K., and Ward, E.J. 2019. Does temporal variability limit standardized biological monitoring at wave and tidal energy sites?. International Marine Energy Journal, 2(1 (Nov), 15–28. [Link to article](https://doi.org/10.36688/imej.2.15-28)

Smits, A.P., Ruffing, C.M., Royer, T.V., Appling, A.P., Griffiths, N.A., Bellmore, R., et al. 2019. Detecting signals of large-scale climate phenomena in discharge and nutrient loads in the Mississippi-Atchafalaya River basin. Geophysical Research Letters, 46, 3791–3801. [Link to article](https://doi.org/10.1029/2018GL081166)

Arnold, L., Scheuerell , M.D., Busch Isaksen 2022. T. Mortality Associated with Extreme Heat in Washington State: The Historical and Projected Public Health Burden. Atmosphere, 13, 1392. [Link to article](https://doi.org/10.3390/atmos13091392)

Elmstrom, E.J., Holtgrieve, G.W., Scheuerell, M.D., Schauer, A.J., and K. Leazer. 2024. Climate and landform interact to control the source and transport of nitrate in Pacific Northwest rivers. Commun Earth Environ 5, 90. [Link to article](https://doi.org/10.1038/s43247-024-01235-8)

Rand, Z.R., Ward, E.J., Zamon, J.E., Good, T.P., and Harvey, C.J. 2024. Using Hidden Markov Models to develop ecosystem indicators from non-stationary time series. Ecological Modelling, Volume 495. [Link to article](https://doi.org/10.1016/j.ecolmodel.2024.110800)



