---
title: "Course overview"
author: "Elizabeth (Eli) Holmes, Mark Scheuerell, Eric Ward"
date: "28 March 2023"
output:
  beamer_presentation: default
  ioslides_presentation: default
subtitle: FISH 550 – Applied Time Series Analysis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introductions

### Who are we?


## Introductions

### Who are you?

### What School/Dept/Program are you from?

### What are you looking to get out this class?  


## Course format

### Flipped lecture format

* Videos posted of the material on the [Lecture tab](https://atsa-es.github.io/atsa/lectures.html). **Watch before class**
* In class time will be devoted to working through hands-on exercises, R coding examples and discussing the content.

### Labs

* Group projects with teams assigned semi-randomly each week
* You will be given a dataset(s) and will come up with a group analysis to do based on the week's material
* Collaborative! Please use the discussion thread on GitHub to ask questions and share solutions with your classmates.


## Communications

### We encourage lots of questions during class

### Use the GitHub [Discussion board](https://github.com/atsa-es/fish550-2023/discussions)

### Feel free to email any of the instructors outside of class

### We will respond within 24 hours


## Grading

__Six group lab write-ups__ (30% of total)  

* Assigned Thurs at the end of computer lab  

* Due by 11:59 PM on the Tues 12 days later  

* Based on material from lectures & computer labs

* Group write-up in RMarkdown or Quarto. A template will be provided.


## Grading

__Research project & paper__ (40% of total)  Must involve some form of time series model(s)

__Two anonymous peer-reviews__ (20% of total) One review each for 2 of your colleague’s papers

### Due Dates

* Project proposal due Fri April 21 11:59pm PDT
* Project methods due Fri May 12 11:59pm PDT
* Final paper due Fri June 2nd 11:59pm PDT
* Presentations May 30 and June 1 during class time and lab time
* Peer review due Fri June 9th 11:59pm PDT


## Grading

__Participation__ (10%)  

* We expect you to show up and interact

* Please contact one of the instructors if you have any conflicts

## chatGPT and Copilot

* You are welcome to use these and they can be powerful coding assistants
* GitHub Copilot is free for students but you need to use VSCode not RStudio
* chatGPT is free if you use on the OpenAI platform
* To use in RStudio, you need to use the API and that cost $
* See the [class website page](https://atsa-es.github.io/atsa/syllabus.html#chatGPT_and_co-pilot) for more info
    

## Expectations for final project

* Research paper or thesis chapter that could result in a peer-reviewed publication

* Focus on applied time series analysis (univariate or multivariate)  
    
* Short format similar to “Report” in _Ecology_ or “Rapid Communication” in _CJFAS_
    - Max of 20 pages, inclusive of refs, tables, figs, etc
    - 12-pt font, double-spaced throughout


## Don't have time series data?

Lots of datasets on the class webpage: [DATASETS](https://atsa-es.github.io/atsa/data_sets.html)

Or talk with the instructors (or your advisor)

## Tech preliminaries

* You will need a GitHub account and accept the invite to join [ATSA-Spring-2023](https://github.com/orgs/atsa-es/teams/atsa-spring-2023)
* Our class repo: [fish550-2023](https://github.com/atsa-es/fish550-2023) with [issues](https://github.com/atsa-es/fish550-2023/issues) and [discussions](https://github.com/atsa-es/fish550-2023/discussions)
* We will use RStudio as our IDE.
* Interacting with GitHub:
  - Option 1: Download GitHub Desktop. Very easy to use platform.
  - Option 2: Connect RStudio to GitHub. 
  - Option 3: Working directly on GitHub.
  - We will help you with these steps on Thursday and will post videos.


## {.flexbox .vcenter .bigger}

<font size="10">
[__Course topics__](https://atsa-es.github.io/atsa) 
</font>

